### ISSUE TITLE
How do I control the size of the whirl?

### ISSUE THREAD

**Issue by geoidesic** [jh3y/whirl#8]

**Comment by jh3y** [comment]
Hey @geoidesic,

I'm due to go over a lot of my projects and update them with new features etc.

But for your query. If you pull down the project and build your own version using the `gulp` commands you should be able to tweak the design to your desire. In `src/less/core.less` (or the sass version) simply alter the `@height` and `@width` variables and then use `gulp less:build` which will generate a new file for you in the `build` folder.

I hope that helps. If not, let me know and we will work out a way to make it easier to use and understand.

@jh3y

**Comment by geoidesic** [comment]
Thanks for the quick reply! I will add an extra class to control the size of the whirl then. Didn't realize it was as easy as just that.

**Comment by jh3y** [comment]
Yeah you can do that or just build a new version which just uses the type of whirl you want. Therefore, cutting down on the file size too! :+1: 

I'll close the issue for now but if you come across anything else let me know.

@jh3y
