### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by apinnecke** [jh3y/whirl#9]
Hey hey,

could you please publish this library to npm in order to make browserify based builds work? Currently one needs to load this one via `npm install -S jh3y/whirl`. Thanks a lot! :)

Unfortunately, `whirl` is already taken on npm, so you also need to find a "new" unique name. =/

**Comment by jh3y** [comment]
Hey @apinnecke 

Understandably publishing to `npm` would be a benefit but I'm not sure I follow as to why it's required to make `browserify` work. You can define your `npm install` to define a version etc. Why does the way in which the package is installed affect how `browserify` behaves with it? It would only be `package.json` that would make any difference no?

As for renaming, I've not got any ideas yet. But, an `npm` package could be named something like `whirl-css` or `whirl-loader` or something along those lines.

I am actually due to revamp `whirl` completely. I have several loading animation sitting in a bookmarked `jsbin` haha.

@jh3y

**Comment by apinnecke** [comment]
> make browserify based builds work

It's not "required", it's just inconvenient currently. At the moment one has to refer to the GitHub repo for installation, which a) requires git to install npm dependencies (which one might not want to have, e.g. in a Docker container) and b) disables several caching layers of npm.

`whirl-loader` sounds awesome. 👍

**Comment by jh3y** [comment]
Hey @apinnecke .

I'm sorry, I never got round to publishing `whirl`. The rework is still on my todo list as the list of prototyped loaders I've created has grown.

I think the best bet is for me to publish under an `npm` scope. Therefore something like;
```shell
npm install @jh3y/whirl
```

Definitely falling into my plans with it being `#hacktoberfest` 🎃 

@jh3y

**Comment by mebibou** [comment]
How's it going with the publishing?

**Comment by jh3y** [comment]
Hey @mebibou 👋 

To be honest, I still need to do this 😅  I've been considering renaming the repo/project so it has a unique name on the `npm` registry and doesn't need to use a scope like `@jh3y/whirl`.

I'm not sure on the implications of publishing as `@jh3y/whirl` for now so that it can be used, then renaming the project and republishing as something else. I'm sure that's likely to be fine 👌 

I also really need to get the `rework` branch published 😅  It's got many more loading animations. I've just been busy with other things.

@jh3y

**Comment by mebibou** [comment]
yeah I think scoping is fine, and it's easy to do on the npm registry (free for open source projects). thanks!

**Comment by jh3y** [comment]
I've just published this from the `CLI` using `@jh3y/whirl` 👍 

Should be available as `1.0.4`. I will try to spend some time on the `rework` branch and get that merged in as there's much more in there.
